export const SHORTCUTS = [
  { action: "Bold", keys: ["Ctrl", "B"] },
  { action: "Italic", keys: ["Ctrl", "I"] },
  { action: "Underline", keys: ["Ctrl", "U"] },
  { action: "Strikethrough", keys: ["Ctrl", "Shift", "S"] },
  { action: "Code (inline)", keys: ["Ctrl", "`"] },
  { action: "Link", keys: ["Ctrl", "K"] },
  { action: "Undo", keys: ["Ctrl", "Z"] },
  { action: "Redo", keys: ["Ctrl", "Y"] },
  { action: "Heading 1", keys: ["Ctrl", "Alt", "1"] },
  { action: "Heading 2", keys: ["Ctrl", "Alt", "2"] },
  { action: "Heading 3", keys: ["Ctrl", "Alt", "3"] },
  { action: "Heading 4", keys: ["Ctrl", "Alt", "4"] },
  { action: "Bullet list", keys: ["Ctrl", "Shift", "8"] },
  { action: "Ordered list", keys: ["Ctrl", "Shift", "7"] },
  { action: "Blockquote", keys: ["Ctrl", "Shift", ">"] },
  { action: "Code block", keys: ["Ctrl", "Alt", "C"] },
  { action: "Horizontal rule", keys: ["---", "Enter"] },
  { action: "Slash commands", keys: ["/"] },
] as const;
